version: '3.7'
services:
  llm_chatbot:
    build:
      context: .
      dockerfile: ./code/Dockerfile
      target: final-islocaldevelopment-true

    volumes:
      - .:/workspace:cached
 
    command: /bin/sh -c "while sleep 1000; do :; done"

